# Generated by Django 3.1.1 on 2020-11-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0003_devicetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
