# Generated by Django 3.1.1 on 2020-10-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedAPI', '0002_remove_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentimage',
            old_name='post',
            new_name='comment',
        ),
    ]
