# Generated by Django 3.1.1 on 2020-11-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedAPI', '0003_auto_20201027_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
